service: sls-python-ec2-start-stop

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-north-1
  profile: serverless-admin
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ec2:*"
          Resource: "*"

functions:
  start-ec2:
    handler: handler.start_ec2
    timeout: 60
    memorySize: 128
    events:
      - schedule: cron(0 20 * * ? *) # Start at 20:00 UTC (my local 22:00 every day)
  stop-ec2:
    handler: handler.stop_ec2
    timeout: 60
    memorySize: 128
    events:
      - schedule: cron(5 20 * * ? *) # Stop at 20:05 UTC (my local 22:05 every day)
